## Numpy - Numeric Python
    Create Multi-dimensional arrays
    Perform Numeric Computtions on data

In [1]:
import numpy as np

In [2]:
empids = [101,102,103]

In [3]:
type(empids)

list

In [5]:
arr1 = np.array([101,102,103])
arr1

array([101, 102, 103])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(3,)

In [8]:
arr2 = np.array([[1,2],[2,3]])

In [11]:
type(arr2)

numpy.ndarray

In [9]:
arr2

array([[1, 2],
       [2, 3]])

In [10]:
arr2.shape

(2, 2)

In [17]:
arr4 = np.array([[1,2,3],[2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [14]:
arr4 = np.array([[1,2,3],[2,0,0]])

In [15]:
arr4

array([[1, 2, 3],
       [2, 0, 0]])

In [20]:
arr4.shape

(2, 3)

In [18]:
arr3 = np.array([[[1,3,4],[2,3,4]]])
arr3

array([[[1, 3, 4],
        [2, 3, 4]]])

In [19]:
arr3.shape

(1, 2, 3)

In [21]:
arr1

array([101, 102, 103])

In [22]:
arr1[0]

np.int64(101)

In [23]:
arr1[1]

np.int64(102)

In [25]:
arr1[2]

np.int64(103)

In [26]:
arr2

array([[1, 2],
       [2, 3]])

In [27]:
arr2.shape

(2, 2)

In [28]:
arr2[0,0]

np.int64(1)

In [29]:
arr2[0,1]

np.int64(2)

In [30]:
arr2[1,1]

np.int64(3)

In [31]:
arr3

array([[[1, 3, 4],
        [2, 3, 4]]])

In [32]:
arr3.shape

(1, 2, 3)

In [33]:
arr3[0,0]

array([1, 3, 4])

In [34]:
arr3[0,0,0]

np.int64(1)

In [35]:
arr3[0,0,2]

np.int64(4)

In [36]:
arr3[0,1]

array([2, 3, 4])

In [37]:
arr3[0,1,0]

np.int64(2)

In [39]:
arr3[0,1,2]

np.int64(4)